import { Platform, StyleSheet } from "react-native";

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#ffffff",
  },
  container: {
    flex: 1,
    backgroundColor: "#ffffff",
    padding: 0,
  },
  navbar: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#f3f4f6",
    backgroundColor: "#f5d902", // Changed to yellow
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 3,
    elevation: 3,
    zIndex: 10,
  },
  navTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#FFFFFF", // Changed to white
  },
  clearButton: {
    padding: 5,
  },
  scrollContent: {
    padding: 20,
    paddingBottom: 20,
  },
  intro: {
    alignItems: "center",
    justifyContent: "center",
    marginTop: 50,
    gap: 16,
  },
  logo: {
    width: 80,
    height: 80,
    borderRadius: 40,
    marginBottom: 20,
  },
  title: {
    fontSize: 26,
    fontWeight: "600",
    color: "#111827",
    textAlign: "center",
  },
  titleAccent: {
    color: "#10b981",
    fontWeight: "700",
  },
  version: {
    fontSize: 14,
    color: "#9ca3af",
    fontWeight: "500",
  },
  subtitle: {
    fontSize: 16,
    color: "#6b7280",
    textAlign: "center",
    marginTop: 6,
  },
  grid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: 12,
    marginTop: 24,
  },
  card: {
    backgroundColor: "#ecfdf5",
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 16,
    elevation: 2,
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
    borderWidth: 1,
    borderColor: "#d1fae5",
  },
  cardText: {
    fontSize: 14,
    fontWeight: "500",
    color: "#059669",
  },
  userBubble: {
    backgroundColor: "#e0f2fe",
    padding: 14,
    borderRadius: 18,
    borderBottomRightRadius: 4,
    alignSelf: "flex-end",
    marginVertical: 8,
    maxWidth: "80%",
    shadowColor: "#000",
    shadowOpacity: 0.04,
    shadowRadius: 3,
    shadowOffset: { width: 0, height: 1 },
    elevation: 1,
  },
  botBubble: {
    backgroundColor: "#f9fafb",
    padding: 14,
    borderRadius: 18,
    borderBottomLeftRadius: 4,
    alignSelf: "flex-start",
    marginVertical: 8,
    maxWidth: "90%",
    shadowColor: "#000",
    shadowOpacity: 0.04,
    shadowRadius: 3,
    shadowOffset: { width: 0, height: 1 },
    elevation: 1,
    borderWidth: 1,
    borderColor: "#f3f4f6",
  },
  loadingBubble: {
    backgroundColor: "#f3f4f6",
    padding: 14,
    borderRadius: 18,
    borderBottomLeftRadius: 4,
    alignSelf: "flex-start",
    marginVertical: 8,
    maxWidth: "90%",
  },
  loadingText: {
    color: "#6b7280",
    fontStyle: "italic",
  },
  errorBubble: {
    backgroundColor: "#fef2f2",
    padding: 14,
    borderRadius: 18,
    borderBottomLeftRadius: 4,
    alignSelf: "flex-start",
    marginVertical: 8,
    maxWidth: "90%",
    borderWidth: 1,
    borderColor: "#fee2e2",
  },
  errorTitle: {
    fontWeight: "600",
    color: "#b91c1c",
    marginBottom: 4,
  },
  errorText: {
    color: "#991b1b",
  },
  imageWrapper: {
    width: "100%",
    alignItems: "center",
    marginBottom: 14,
  },
  image: {
    width: 320,
    height: 180,
    borderRadius: 16,
    backgroundColor: "#e5e7eb",
  },
  messageText: {
    fontSize: 15,
    color: "#111827",
    lineHeight: 22,
  },
  iconBtn: {
    marginTop: 8,
    alignSelf: "flex-end",
    padding: 4,
  },
  inputContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    padding: 16,
    paddingBottom: 0,
    backgroundColor: "#ffffff",
    borderTopWidth: 1,
    borderColor: "#e5e7eb",
    // Remove position: 'absolute' to prevent it from hiding behind keyboard
    bottom: 0,
    left: 0,
    right: 0,
    shadowColor: "#000",
    shadowOpacity: 0.08,
    shadowRadius: 5,
    shadowOffset: { width: 0, height: -3 },
    elevation: 5,
  },
  input: {
    flex: 1,
    fontSize: 16,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#d1d5db",
    backgroundColor: "#f9fafb",
    color: "#111827",
  },
  sendBtn: {
    backgroundColor: "#ecfdf5",
    padding: 12,
    borderRadius: 999,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowRadius: 3,
    shadowOffset: { width: 0, height: 1 },
    elevation: 2,
    borderWidth: 1,
    borderColor: "#d1fae5",
  },
  sendBtnDisabled: {
    backgroundColor: "#f9fafb",
    borderColor: "#e5e7eb",
  },
  sourcesContainer: {
    marginTop: 16,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: "#e5e7eb",
    width: "auto",
  },
  sourcesTitle: {
    fontSize: 14,
    fontWeight: "600",
    color: "#4b5563",
    marginBottom: 10,
  },
  sourceBox: {
    backgroundColor: "#f9fafb",
    borderWidth: 1,
    borderColor: "#d1d5db",
    borderRadius: 20,
    paddingVertical: 8,
    paddingHorizontal: 14,
    marginBottom: 8,
  },
  sourceName: {
    fontSize: 13,
    color: "#4b5563",
    fontWeight: "500",
  },
});

export default styles;
