import { Platform, StyleSheet } from "react-native";

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#ffffff",
  },
  container: {
    flex: 1,
    backgroundColor: "#ffffff",
    padding: 0,
  },
  navbar: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#f3f4f6",
    backgroundColor: "#f5d902",
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 3,
    elevation: 3,
    zIndex: 10,
  },
  navTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#FFFFFF",
  },
  clearButton: {
    padding: 5,
  },
  scrollContent: {
    padding: 20,
    paddingBottom: 20,
  },

  // ==================== HOME SCREEN STYLES ====================
  intro: {
    alignItems: "center",
    justifyContent: "center",
    marginTop: Platform.OS === "ios" ? 40 : 30,
    gap: 16,
    paddingHorizontal: 20,
  },
  logoContainer: {
    position: "relative",
    marginBottom: 16,
  },
  logo: {
    width: 120,
    height: 120,
    borderRadius: 60,
    zIndex: 2,
    borderWidth: 4,
    borderColor: "#FFFFFF",
    backgroundColor: "#10b981",
    justifyContent: "center",
    alignItems: "center",
  },
  logoGlow: {
    position: "absolute",
    width: 130,
    height: 130,
    borderRadius: 65,
    backgroundColor: "rgba(16, 185, 129, 0.2)",
    top: -5,
    left: -5,
    zIndex: 1,
  },
  logoInnerGlow: {
    position: "absolute",
    width: 124,
    height: 124,
    borderRadius: 62,
    borderWidth: 8,
    borderColor: "rgba(255, 255, 255, 0.15)",
  },
  title: {
    fontSize: 34,
    fontWeight: "500",
    color: "#1F2937",
    textAlign: "center",
    letterSpacing: -0.8,
    marginTop: 10,
  },
  titleAccent: {
    color: "#10b981",
    fontWeight: "500",
  },
  subtitle: {
    fontSize: 16,
    color: "#6b7280",
    textAlign: "center",
    marginBottom: 8,
    fontFamily: Platform.OS === "ios" ? "Helvetica Neue" : "sans-serif",
    lineHeight: 24,
    maxWidth: "80%",
  },
  grid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    gap: 16,
    marginTop: 30,
    width: "100%",
  },
  card: {
    width: "48%",
    padding: 22,
    borderRadius: 24,
    elevation: 4,
    shadowColor: "#000",
    shadowOpacity: 0.15,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    minHeight: 160,
    justifyContent: "space-between",
    overflow: "hidden",
  },
  cardGradient: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    opacity: 0.9,
  },
  cardContent: {
    zIndex: 2,
  },
  cardIcon: {
    fontSize: 32,
    marginBottom: 16,
    textShadowColor: "rgba(0,0,0,0.1)",
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  cardText: {
    fontSize: 16,
    fontWeight: "700",
    color: "#FFFFFF",
    lineHeight: 22,
    textShadowColor: "rgba(0,0,0,0.2)",
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  watermark: {
    marginTop: 40,
    paddingVertical: 14,
    paddingHorizontal: 28,
    backgroundColor: "#F3F4F6",
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  watermarkText: {
    fontSize: 15,
    color: "#6B7280",
    fontWeight: "500",
    fontStyle: "italic",
  },
  // ==================== END HOME SCREEN STYLES ====================

  // ==================== CHAT STYLES (unchanged) ====================
  userBubble: {
    backgroundColor: "#e0f2fe",
    padding: 14,
    borderRadius: 18,
    borderBottomRightRadius: 4,
    alignSelf: "flex-end",
    marginVertical: 8,
    maxWidth: "80%",
    shadowColor: "#000",
    shadowOpacity: 0.04,
    shadowRadius: 3,
    shadowOffset: { width: 0, height: 1 },
    elevation: 1,
  },
  botBubble: {
    backgroundColor: "#f9fafb",
    padding: 14,
    borderRadius: 18,
    borderBottomLeftRadius: 4,
    alignSelf: "flex-start",
    marginVertical: 8,
    maxWidth: "90%",
    shadowColor: "#000",
    shadowOpacity: 0.04,
    shadowRadius: 3,
    shadowOffset: { width: 0, height: 1 },
    elevation: 1,
    borderWidth: 1,
    borderColor: "#f3f4f6",
  },
  loadingBubble: {
    backgroundColor: "#f3f4f6",
    padding: 14,
    borderRadius: 18,
    borderBottomLeftRadius: 4,
    alignSelf: "flex-start",
    marginVertical: 8,
    maxWidth: "90%",
  },
  loadingText: {
    color: "#6b7280",
    fontStyle: "italic",
  },
  errorBubble: {
    backgroundColor: "#fef2f2",
    padding: 14,
    borderRadius: 18,
    borderBottomLeftRadius: 4,
    alignSelf: "flex-start",
    marginVertical: 8,
    maxWidth: "90%",
    borderWidth: 1,
    borderColor: "#fee2e2",
  },
  errorTitle: {
    fontWeight: "600",
    color: "#b91c1c",
    marginBottom: 4,
  },
  errorText: {
    color: "#991b1b",
  },
  imageWrapper: {
    width: "100%",
    alignItems: "center",
    marginBottom: 14,
  },
  image: {
    width: 320,
    height: 180,
    borderRadius: 16,
    backgroundColor: "#e5e7eb",
  },
  messageText: {
    fontSize: 15,
    color: "#111827",
    lineHeight: 22,
  },
  iconBtn: {
    marginTop: 8,
    alignSelf: "flex-end",
    padding: 4,
  },
  inputContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    padding: 16,
    paddingBottom: Platform.OS === "ios" ? 30 : 16,
    backgroundColor: "#ffffff",
    borderTopWidth: 1,
    borderColor: "#e5e7eb",
    bottom: 0,
    left: 0,
    right: 0,
    shadowColor: "#000",
    shadowOpacity: 0.08,
    shadowRadius: 5,
    shadowOffset: { width: 0, height: -3 },
    elevation: 5,
  },
  input: {
    flex: 1,
    fontSize: 16,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#d1d5db",
    backgroundColor: "#f9fafb",
    color: "#111827",
  },
  sendBtn: {
    backgroundColor: "#ecfdf5",
    padding: 12,
    borderRadius: 999,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowRadius: 3,
    shadowOffset: { width: 0, height: 1 },
    elevation: 2,
    borderWidth: 1,
    borderColor: "#d1fae5",
  },
  sendBtnDisabled: {
    backgroundColor: "#f9fafb",
    borderColor: "#e5e7eb",
  },
  sourcesContainer: {
    marginTop: 16,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: "#e5e7eb",
    width: "auto",
  },
  sourcesTitle: {
    fontSize: 14,
    fontWeight: "600",
    color: "#4b5563",
    marginBottom: 10,
  },
  sourceBox: {
    backgroundColor: "#f9fafb",
    borderWidth: 1,
    borderColor: "#d1d5db",
    borderRadius: 20,
    paddingVertical: 8,
    paddingHorizontal: 14,
    marginBottom: 8,
  },
  sourceName: {
    fontSize: 13,
    color: "#4b5563",
    fontWeight: "500",
  },
  version: {
    fontSize: 14,
    color: "#9ca3af",
    fontWeight: "500",
  },
  gridContainer: {
    width: "100%",
    marginTop: 30,
  },
  gridRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 16,
  },
  gridCard: {
    width: "48%",
    aspectRatio: 1,
    borderRadius: 20,
    padding: 16,
    justifyContent: "center",
    alignItems: "center",
    elevation: 4,
    // shadowColor: "#000",
    // shadowOpacity: 0.2,
    // shadowRadius: 6,
    // shadowOffset: { width: 0, height: 4 },
  },
  gridCardWide: {
    width: "100%",
    aspectRatio: 2.5,
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
  },
  gridCardIcon: {
    fontSize: 36,
    marginBottom: 12,
  },
  gridCardText: {
    fontSize: 16,
    fontWeight: "500",
    color: "#FFFFFF",
    textAlign: "center",
    textShadowColor: "rgba(0,0,0,0.2)",
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
});

export default styles;
